// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

const data = [
  { id:'1',
  name: 'Susnata Chatterjee',
  url:"/Artists-Artworks/SusnataChatterjee/himachal.jpeg",},
  { id:'2',
  name: 'Subrata Ghosh',
  url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg",},
  { id:'3',
  name: 'Titas Das',
  url:"/Artists-Artworks/TitasDas/submergediv.jpg",},
  { id:'4',
  name: 'Mitali Roy Choudhury',
  url:"/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg",},
  { id:'5',
  name: 'Shayani Boral',
  url:"/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg",},
  { id:'6',
  name: 'Prithuj Mondal',
  url:"/Artists-Artworks/PrithujMondal/conversation.jpg",},
  { id:'7',
  name: 'Preeti Sethi',
  url:"/Artists-Artworks/PreetiSethi/16.jpg",},
  { id:'8',
  name: 'Debangsu Biswas',
  url:"/Artists-Artworks/DebangsuBiswas/1.jpg",},
  { id:'9',
  name: 'Meenu Garg',
  url:"/Artists-Artworks/Meenugarg/1 (1).png",},
  { id:'10',
  name: 'Balwinder Tanwar',
  url:"/Artists-Artworks/BalwinderTanwar/1 (3).jpg",},
]

export default data;