// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

const data = [
  { id:'1',
  name: 'Susnata Chatterjee',
  url:"/Artists-Artworks/SusnataChatterjee/himachal.jpeg",
  artistcategory:"Featured"},
  { id:'2',
  name: 'Subrata Ghosh',
  url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg",
  artistcategory:"Spotlight"},
  { id:'3',
  name: 'Titas Das',
  url:"/Artists-Artworks/TitasDas/submergediv.jpg",
  artistcategory:"Featured"},
  { id:'4',
  name: 'Shayani Boral',
  url:"/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg",
  artistcategory:"Featured"},
  { id:'5',
  name: 'Prithuj Mondal',
  url:"/Artists-Artworks/PrithujMondal/conversation.jpg",
  artistcategory:"Spotlight"},
  { id:'6',
  name: 'Preeti Sethi',
  url:"/Artists-Artworks/PreetiSethi/16.jpg",
  artistcategory:"Spotlight"},
  { id:'7',
  name: 'Debangsu Biswas',
  url:"/Artists-Artworks/DebangsuBiswas/1.jpg",
  artistcategory:"Featured"},
  { id:'8',
  name: 'Meenu Garg',
  url:"/Artists-Artworks/Meenugarg/1 (1).png",
  artistcategory:"Featured"},
  { id:'9',
  name: 'Balwinder Tanwar',
  url:"/Artists-Artworks/BalwinderTanwar/1 (3).jpg",
  artistcategory:"Featured"},
  { id:'10',
    name: 'Ravindra Kumar Tanwar',
    url:"/Artists-Artworks/RavindraKumarTanwar/2.jpg",
    artistcategory:"Featured"},
  { id:'11',
    name: 'Pabitra Pal',
    url:"/Artists-Artworks/PabitraPal/Wingspabitra1.jpg",
    artistcategory:"Featured"},
  { id:'12',
    name: 'Harsh Inder Loomba',
    url:"/Artists-Artworks/HarshInderLoomba/1.jpg",
    artistcategory:"Spotlight"},
  { id:'13',
    name: 'Ajay Samir',
    url:"/Artists-Artworks/AjaySamir/1.jpg",
    artistcategory:"Spotlight"},
    { id:'14',
      name: 'Seema',
      url:"/Artists-Artworks/AjaySamir/1.jpg",
      artistcategory:"Spotlight"},
      { id:'15',
        name: 'Hema',
        url:"/Artists-Artworks/Hema/1.jpg",
        artistcategory:"Spotlight"},
  
]

export default data;