const artworks = [
{id:'1',
title:"Himachal",
desc:"Himachal",
url:"/Artists-Artworks/SusnataChatterjee/himachal.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/himachal.jpeg","/Artists-Artworks/SusnataChatterjee/himachal.jpeg","/Artists-Artworks/SusnataChatterjee/himachal.jpeg","/Artists-Artworks/SusnataChatterjee/himachal.jpeg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["24 x 30 inches","Watercolour on Paper","Original","2024"]
},
{id:'2',
title:"Landscape",
desc:"Landscape",
url:"/Artists-Artworks/SusnataChatterjee/landscape.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/landscape.jpeg","/Artists-Artworks/SusnataChatterjee/landscape.jpeg","/Artists-Artworks/SusnataChatterjee/landscape.jpeg","/Artists-Artworks/SusnataChatterjee/landscape.jpeg"],
genre:'figurative',
medium:'paintings',
price:"73000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["30 x 40 inches","Acrylic on Canvas","Original","2023"]
},
{id:'3',
title:"Photosynthesis",
desc:"Photosynthesis",
url:"/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg","/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg","/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg","/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg"],
genre:'figurative',
medium:'paintings',
price:"82000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["36 x 42 inches","Acrylic on Canvas","Original","2023"]
},
{id:'4',
title:"Village 2",
desc:"Village 2",
url:"/Artists-Artworks/SusnataChatterjee/village2.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/village2.jpeg","/Artists-Artworks/SusnataChatterjee/village2.jpeg","/Artists-Artworks/SusnataChatterjee/village2.jpeg","/Artists-Artworks/SusnataChatterjee/village2.jpeg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["24 x 30 inches","Watercolour on Paper","Original","2024"]
},
{id:'5',
title:"Peace 1",
desc:"Peace 1",
url:"/Artists-Artworks/SusnataChatterjee/peace.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/peace.jpeg","/Artists-Artworks/SusnataChatterjee/peace.jpeg","/Artists-Artworks/SusnataChatterjee/peace.jpeg","/Artists-Artworks/SusnataChatterjee/peace.jpeg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["24 x 30 inches","Watercolour on Paper","Original","2024"]
},
{id:'6',
title:"Peace 2",
desc:"Peace 2",
url:"/Artists-Artworks/SusnataChatterjee/peace2.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/peace2.jpeg","/Artists-Artworks/SusnataChatterjee/peace2.jpeg","/Artists-Artworks/SusnataChatterjee/peace2.jpeg","/Artists-Artworks/SusnataChatterjee/peace2.jpeg"],
genre:'figurative',
medium:'paintings',
price:"82000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["36 x 42 inches","Acrylic on Canvas","Original","2023"]
},
{id:'7',
title:"Evening",
desc:"Evening",
url:"/Artists-Artworks/SusnataChatterjee/evening.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/evening.jpeg","/Artists-Artworks/SusnataChatterjee/evening.jpeg","/Artists-Artworks/SusnataChatterjee/evening.jpeg","/Artists-Artworks/SusnataChatterjee/evening.jpeg"],
genre:'figurative',
medium:'paintings',
price:"28000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["24 x 30 inches","Acrylic on Canvas","Original","2024"]
},
{id:'8',
title:"Friends",
desc:"Friends",
url:"/Artists-Artworks/SusnataChatterjee/friends.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/friends.jpeg","/Artists-Artworks/SusnataChatterjee/friends.jpeg","/Artists-Artworks/SusnataChatterjee/friends.jpeg","/Artists-Artworks/SusnataChatterjee/friends.jpeg"],
genre:'figurative',
medium:'paintings',
price:"82000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["36 x 42 inches","Acrylic on Canvas","Original","2023"]
},
{id:'9',
title:"The Moon and The Hill Station",
desc:"The Moon and The Hill Station",
url:"/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg"],
genre:'figurative',
medium:'paintings',
price:"82000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["36 x 42 inches","Acrylic on Canvas","Original",""]
},
{id:'10',
title:"Moon and Village",
desc:"Moon and Village",
url:"/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg","/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg","/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg","/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg"],
genre:'figurative',
medium:'paintings',
price:"64000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["30 x 36 inches","Acrylic on Canvas","Original","2024"]
},
{id:'11',
title:"The Moon and The Village",
desc:"The Moon and The Village",
url:"/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg"],
genre:'figurative',
medium:'paintings',
price:"37000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["30 x 36 inches","Acrylic on Canvas","Original","2024"]
},
// {id:'12',
// title:"Bija/ Hope 1",
// desc:"Bija/ Hope 1",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["13 x 11 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'13',
// title:"Bija/ Hope 2",
// desc:"Bija/ Hope 2",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["13 x 11 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'14',
// title:"Bija/ Hope 3",
// desc:"Bija/ Hope 3",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["13 x 11 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'15',
// title:"Bija/ Hope 4",
// desc:"Bija/ Hope 4",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["13 x 13 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'16',
// title:"Bija/ Hope 5",
// desc:"Bija/ Hope 5",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["13 x 13 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'17',
// title:"Bija/ Hope 6",
// desc:"Bija/ Hope 6",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["13 x 13 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'18',
// title:"Bija/ Hope 7",
// desc:"Bija/ Hope 7",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["13 x 13 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'19',
// title:"Bija/ Hope 8",
// desc:"Bija/ Hope 8",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["14 x 11 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'20',
// title:"Bija/ Hope 9",
// desc:"Bija/ Hope 9",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["15 x 15 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'21',
// title:"Bija/ Hope 10",
// desc:"Bija/ Hope 10",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["15 x 15 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'22',
// title:"Bija/ Hope 11",
// desc:"Bija/ Hope 11",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["15 x 15 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'23',
// title:"Bija/ Hope 12",
// desc:"Bija/ Hope 12",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["20 x 20 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'24',
// title:"Bija/ Hope 13",
// desc:"Bija/ Hope 13",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"25000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["20 x 20 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'25',
// title:"Bija/ Hope 14",
// desc:"Bija/ Hope 14",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"35000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["32 x 30 inches","Acrylic on Canvas","Original","2024"]
// },
// {id:'26',
// title:"Bija/ Hope 15",
// desc:"Bija/ Hope 15",
// url:"/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg",
// images:["/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"35000",
// artistid:'2',
// artistname:'Subrata Ghosh',
// details:["30 x 36 inches","Acrylic on Canvas","Original","2024"]
// },
{id:'27',
title:"Submerged IV",
desc:"Submerged IV",
url:"/Artists-Artworks/TitasDas/submergediv.jpg",
images:["/Artists-Artworks/TitasDas/submergediv.jpg","/Artists-Artworks/TitasDas/submergediv.jpg","/Artists-Artworks/TitasDas/submergediv.jpg","/Artists-Artworks/TitasDas/submergediv.jpg"],
genre:'figurative',
medium:'paintings',
price:"99000",
artistid:'3',
artistname:'Titas Das',
details:["48 x 56 inches","Acrylic on Canvas","Original","2023"]
},
{id:'28',
title:"Submerged IX",
desc:"Submerged IX",
url:"/Artists-Artworks/TitasDas/submergedix.jpg",
images:["/Artists-Artworks/TitasDas/submergedix.jpg","/Artists-Artworks/TitasDas/submergedix.jpg","/Artists-Artworks/TitasDas/submergedix.jpg","/Artists-Artworks/TitasDas/submergedix.jpg"],
genre:'figurative',
medium:'paintings',
price:"99000",
artistid:'3',
artistname:'Titas Das',
details:["48 x 56 inches","Acrylic on Canvas","Original","2023"]
},
{id:'29',
title:"Submerged X",
desc:"Submerged X",
url:"/Artists-Artworks/TitasDas/submergedx.jpg",
images:["/Artists-Artworks/TitasDas/submergedx.jpg","/Artists-Artworks/TitasDas/submergedx.jpg","/Artists-Artworks/TitasDas/submergedx.jpg","/Artists-Artworks/TitasDas/submergedx.jpg"],
genre:'figurative',
medium:'paintings',
price:"99000",
artistid:'3',
artistname:'Titas Das',
details:["48 x 56 inches","Acrylic on Canvas","Original","2023"]
},
{id:'30',
title:"Submerged XI",
desc:"Submerged XI",
url:"/Artists-Artworks/TitasDas/submergedxi.jpg",
images:["/Artists-Artworks/TitasDas/submergedxi.jpg","/Artists-Artworks/TitasDas/submergedxi.jpg","/Artists-Artworks/TitasDas/submergedxi.jpg","/Artists-Artworks/TitasDas/submergedxi.jpg"],
genre:'figurative',
medium:'paintings',
price:"79000",
artistid:'3',
artistname:'Titas Das',
details:["32 x 56 inches","Acrylic on Canvas","Original","2023"]
},
{id:'31',
title:"Submerged XXXIII",
desc:"Submerged XXXIII",
url:"/Artists-Artworks/TitasDas/submergedxxxiii.jpg",
images:["/Artists-Artworks/TitasDas/submergedxxxiii.jpg","/Artists-Artworks/TitasDas/submergedxxxiii.jpg","/Artists-Artworks/TitasDas/submergedxxxiii.jpg","/Artists-Artworks/TitasDas/submergedxxxiii.jpg"],
genre:'figurative',
medium:'paintings',
price:"69000",
artistid:'3',
artistname:'Titas Das',
details:["30 x 48 inches","Acrylic on Canvas","Original","2023"]
},
// {id:'32',
// title:"Sadhna",
// desc:"Sadhna",
// url:"/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg",
// images:["/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg","/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg","/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg","/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"9000",
// artistid:'4',
// artistname:'Mitali Roy Choudhury',
// details:["24 x 24 inches","Applique Work on Canvas","Original","2024"]
// },
// {id:'33',
// title:"O Deer",
// desc:"O Deer",
// url:"/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg",
// images:["/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg","/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg","/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg","/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"7000",
// artistid:'4',
// artistname:'Mitali Roy Choudhury',
// details:["17 x 37 inches","Applique Work on Canvas","Original","2024"]
// },
// {id:'34',
// title:"City Roads",
// desc:"City Roads",
// url:"/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg",
// images:["/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg","/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg","/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg","/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"7000",
// artistid:'4',
// artistname:'Mitali Roy Choudhury',
// details:["17 x 37 inches","Applique Work on Canvas","Original","2024"]
// },
// {id:'35',
// title:"Lotus Pond",
// desc:"Lotus Pond",
// url:"/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg",
// images:["/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg","/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg","/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg","/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg"],
// genre:'figurative',
// medium:'paintings',
// price:"7000",
// artistid:'4',
// artistname:'Mitali Roy Choudhury',
// details:["17 x 37 inches","Applique Work on Cloth","Original","2024"]
// },
{id:'36',
title:"Discuss",
desc:"Discuss",
url:"/Artists-Artworks/ShayaniBoral/discuss.jpg",
images:["/Artists-Artworks/ShayaniBoral/discuss.jpg","/Artists-Artworks/ShayaniBoral/discuss.jpg","/Artists-Artworks/ShayaniBoral/discuss.jpg","/Artists-Artworks/ShayaniBoral/discuss.jpg"],
genre:'figurative',
medium:'paintings',
price:"50000",
artistid:'4',
artistname:'Shayani Boral',
details:["48 x 60 inches","Acrylic (mixed media)","Original",""]
},
{id:'37',
title:"The Garden of Galleria",
desc:"The Garden of Galleria",
url:"/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg",
images:["/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg","/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg","/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg","/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg"],
genre:'figurative',
medium:'paintings',
price:"150000",
artistid:'4',
artistname:'Shayani Boral',
details:["82 x 55 inches","Mixed Media on Canvas","Original",""]
},
{id:'38',
title:"Turtle's Tapestry",
desc:"Turtle's Tapestry",
url:"/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg",
images:["/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg","/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg","/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg","/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg"],
genre:'figurative',
medium:'paintings',
price:"50000",
artistid:'4',
artistname:'Shayani Boral',
details:["48 x 36 inches","Ink, Brush, Pen & Acrylic (mixed media)","Original",""]
},
{id:'39',
title:"Resonance of Nature",
desc:"Resonance of Nature",
url:"/Artists-Artworks/ShayaniBoral/resonanceofnature.JPG",
images:["/Artists-Artworks/ShayaniBoral/resonanceofnature.JPG","/Artists-Artworks/ShayaniBoral/resonanceofnature.JPG","/Artists-Artworks/ShayaniBoral/resonanceofnature.JPG","/Artists-Artworks/ShayaniBoral/resonanceofnature.JPG"],
genre:'figurative',
medium:'paintings',
price:"50000",
artistid:'4',
artistname:'Shayani Boral',
details:["48 x 60 inches","Acrylic on Canvas","Original",""]
},
{id:'40',
title:"Turmoil in Sea Bed",
desc:"Turmoil in Sea Bed",
url:"/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg",
images:["/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg","/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg","/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg","/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg"],
genre:'figurative',
medium:'paintings',
price:"500000",
artistid:'4',
artistname:'Shayani Boral',
details:["48 x 60 inches","Mixed Media on Canvas","Original",""]
},
{id:'41',
title:"Urban Drought",
desc:"Urban Drought",
url:"/Artists-Artworks/ShayaniBoral/urbandrought.JPG",
images:["/Artists-Artworks/ShayaniBoral/urbandrought.JPG","/Artists-Artworks/ShayaniBoral/urbandrought.JPG","/Artists-Artworks/ShayaniBoral/urbandrought.JPG","/Artists-Artworks/ShayaniBoral/urbandrought.JPG"],
genre:'figurative',
medium:'paintings',
price:"150000",
artistid:'4',
artistname:'Shayani Boral',
details:["8ft x 4ft","Mixed Media on Canvas","Original",""]
},
{id:'42',
title:"Urban Traffic",
desc:"Urban Traffic",
url:"/Artists-Artworks/ShayaniBoral/urbantraffic.jpg",
images:["/Artists-Artworks/ShayaniBoral/urbantraffic.jpg","/Artists-Artworks/ShayaniBoral/urbantraffic.jpg","/Artists-Artworks/ShayaniBoral/urbantraffic.jpg","/Artists-Artworks/ShayaniBoral/urbantraffic.jpg"],
genre:'figurative',
medium:'paintings',
price:"350000",
artistid:'4',
artistname:'Shayani Boral',
details:["28 x 30 inches","Mixed Media on Canvas","Original",""]
},
{id:'43',
title:"Urban Check Mate",
desc:"Urban Check Mate",
url:"/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg",
images:["/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg","/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg","/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg","/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg"],
genre:'figurative',
medium:'paintings',
price:"150000",
artistid:'4',
artistname:'Shayani Boral',
details:["48 x 54 inches","Mixed Media on Canvas","Original",""]
},
{id:'44',
title:"1000 Miles",
desc:"1000 Miles",
url:"/Artists-Artworks/PrithujMondal/HYYYY.JPG",
images:["/Artists-Artworks/PrithujMondal/HYYYY.JPG","/Artists-Artworks/PrithujMondal/HYYYY.JPG","/Artists-Artworks/PrithujMondal/HYYYY.JPG","/Artists-Artworks/PrithujMondal/HYYYY.JPG"],
genre:'figurative',
medium:'paintings',
price:"150000",
artistid:'5',
artistname:'Prithuj Mondal',
details:["72 x 48 inches","Dry Pastel on Paper","Original","2020"]
},
{id:'45',
title:"Conversation",
desc:"Conversation",
url:"/Artists-Artworks/PrithujMondal/conversation.jpg",
images:["/Artists-Artworks/PrithujMondal/conversation.jpg","/Artists-Artworks/PrithujMondal/conversation.jpg","/Artists-Artworks/PrithujMondal/conversation.jpg","/Artists-Artworks/PrithujMondal/conversation.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'5',
artistname:'Prithuj Mondal',
details:["24 x 24 inches","Acrylic on Canvas","Original","2022"]
},
{id:'46',
title:"Once Upon a Time",
desc:"Once Upon a Time",
url:"/Artists-Artworks/PrithujMondal/onceuponatime.jpg",
images:["/Artists-Artworks/PrithujMondal/onceuponatime.jpg","/Artists-Artworks/PrithujMondal/onceuponatime.jpg","/Artists-Artworks/PrithujMondal/onceuponatime.jpg","/Artists-Artworks/PrithujMondal/onceuponatime.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'5',
artistname:'Prithuj Mondal',
details:["24 x 24 inches","Acrylic on Canvas","Original","2022"]
},
{id:'47',
title:"The Angels",
desc:"The Angels",
url:"/Artists-Artworks/PrithujMondal/theangels.jpg",
images:["/Artists-Artworks/PrithujMondal/theangels.jpg","/Artists-Artworks/PrithujMondal/theangels.jpg","/Artists-Artworks/PrithujMondal/theangels.jpg","/Artists-Artworks/PrithujMondal/theangels.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'5',
artistname:'Prithuj Mondal',
details:["24 x 24 inches","Acrylic on Canvas","Original","2022"]
},
{id:'48',
title:"Untitled",
desc:"Untitled",
url:"/Artists-Artworks/PrithujMondal/untitled.jpg",
images:["/Artists-Artworks/PrithujMondal/untitled.jpg","/Artists-Artworks/PrithujMondal/untitled.jpg","/Artists-Artworks/PrithujMondal/untitled.jpg","/Artists-Artworks/PrithujMondal/untitled.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'5',
artistname:'Prithuj Mondal',
details:["24 x 24 inches","Acrylic on Canvas","Original","2022"]
},
{id:'49',
title:"Moods",
desc:"Moods",
url:"/Artists-Artworks/PreetiSethi/2.jpg",
images:["/Artists-Artworks/PreetiSethi/2.jpg","/Artists-Artworks/PreetiSethi/2.jpg","/Artists-Artworks/PreetiSethi/2.jpg","/Artists-Artworks/PreetiSethi/2.jpg"],
genre:'figurative',
medium:'paintings',
price:"15000",
artistid:'6',
artistname:'Preeti Sethi',
details:["A4","Print on Archival Paper","Original",""]
},
{id:'50',
title:"The Leap",
desc:"The Leap",
url:"/Artists-Artworks/PreetiSethi/3.jpg",
images:["/Artists-Artworks/PreetiSethi/3.jpg","/Artists-Artworks/PreetiSethi/3.jpg","/Artists-Artworks/PreetiSethi/3.jpg","/Artists-Artworks/PreetiSethi/3.jpg"],
genre:'figurative',
medium:'sculptures',
price:"295000",
artistid:'6',
artistname:'Preeti Sethi',
details:["24 x 36 inches","Mixed Media (Brass Metal Art) on Canvas","Original",""]
},
{id:'51',
title:"Amba's Pratishodh",
desc:"Amba's Pratishodh",
url:"/Artists-Artworks/PreetiSethi/4.jpg",
images:["/Artists-Artworks/PreetiSethi/4.jpg","/Artists-Artworks/PreetiSethi/5.jpg","/Artists-Artworks/PreetiSethi/41.jpg","/Artists-Artworks/PreetiSethi/4.jpg"],
genre:'figurative',
medium:'sculptures',
price:"125000",
artistid:'6',
artistname:'Preeti Sethi',
details:["18 inches","Fibre","Original",""]
},
{id:'52',
title:"Karma",
desc:"Was selected to be exhibited at the XIV th Florence Biennale Italy 2023 ( I did not participate due to personal issues)",
url:"/Artists-Artworks/PreetiSethi/6.jpg",
images:["/Artists-Artworks/PreetiSethi/6.jpg","/Artists-Artworks/PreetiSethi/6.jpg","/Artists-Artworks/PreetiSethi/6.jpg","/Artists-Artworks/PreetiSethi/6.jpg"],
genre:'figurative',
medium:'paintings',
price:"110000",
artistid:'6',
artistname:'Preeti Sethi',
details:["3 x 4 ft","Mixed Media on Canvas","Original",""]
},
{id:'53',
title:"It's a Girl!!!!",
desc:"Was exhibited at the XIIIth Florence Biennale Italy 2021",
url:"/Artists-Artworks/PreetiSethi/7.jpg",
images:["/Artists-Artworks/PreetiSethi/7.jpg","/Artists-Artworks/PreetiSethi/7.jpg","/Artists-Artworks/PreetiSethi/7.jpg","/Artists-Artworks/PreetiSethi/7.jpg"],
genre:'figurative',
medium:'sculptures',
price:"On Request",
artistid:'6',
artistname:'Preeti Sethi',
details:["12 x 12 inches","Mixed Medium Clay Sculpture ","Original",""]
},
{id:'54',
title:"Might",
desc:"Might",
url:"/Artists-Artworks/PreetiSethi/8.jpg",
images:["/Artists-Artworks/PreetiSethi/8.jpg","/Artists-Artworks/PreetiSethi/8.jpg","/Artists-Artworks/PreetiSethi/8.jpg","/Artists-Artworks/PreetiSethi/8.jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'6',
artistname:'Preeti Sethi',
details:["10 x 10 inches","Mixed Media on Paper","Original",""]
},
{id:'55',
title:"Lust",
desc:"Lust",
url:"/Artists-Artworks/PreetiSethi/9.jpg",
images:["/Artists-Artworks/PreetiSethi/9.jpg","/Artists-Artworks/PreetiSethi/9.jpg","/Artists-Artworks/PreetiSethi/9.jpg","/Artists-Artworks/PreetiSethi/9.jpg"],
genre:'figurative',
medium:'paintings',
price:"35000",
artistid:'6',
artistname:'Preeti Sethi',
details:["10 x 10 inches","Mixed Media on Paper","Original",""]
},
{id:'56',
title:"Tattered Wings and Shattered Dreams",
desc:"Tattered Wings and Shattered Dreams",
url:"/Artists-Artworks/PreetiSethi/10.jpg",
images:["/Artists-Artworks/PreetiSethi/10.jpg","/Artists-Artworks/PreetiSethi/10.jpg","/Artists-Artworks/PreetiSethi/10.jpg","/Artists-Artworks/PreetiSethi/10.jpg"],
genre:'figurative',
medium:'paintings',
price:"35000",
artistid:'6',
artistname:'Preeti Sethi',
details:["10 x 10 inches","Color Pencils on paper","Original",""]
},
{id:'57',
title:"Eklavyas Gurudhakshina",
desc:"Eklavyas Gurudhakshina",
url:"/Artists-Artworks/PreetiSethi/11.jpg",
images:["/Artists-Artworks/PreetiSethi/11.jpg","/Artists-Artworks/PreetiSethi/11.jpg","/Artists-Artworks/PreetiSethi/11.jpg","/Artists-Artworks/PreetiSethi/11.jpg"],
genre:'figurative',
medium:'sculptures',
price:"105000",
artistid:'6',
artistname:'Preeti Sethi',
details:["18 inches","Fibre Sculpture","Original",""]
},
{id:'58',
title:"Pawns-1",
desc:"Pawns-1",
url:"/Artists-Artworks/PreetiSethi/12.jpg",
images:["/Artists-Artworks/PreetiSethi/12.jpg","/Artists-Artworks/PreetiSethi/12.jpg","/Artists-Artworks/PreetiSethi/12.jpg","/Artists-Artworks/PreetiSethi/12.jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'6',
artistname:'Preeti Sethi',
details:["12 x 12 inches","Acrylic on Canvas","Original",""]
},
{id:'59',
title:"Scars-2",
desc:"Scars-2",
url:"/Artists-Artworks/PreetiSethi/13.jpg",
images:["/Artists-Artworks/PreetiSethi/13.jpg","/Artists-Artworks/PreetiSethi/13.jpg","/Artists-Artworks/PreetiSethi/13.jpg","/Artists-Artworks/PreetiSethi/13.jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'6',
artistname:'Preeti Sethi',
details:["10 x 10 inches","Mixed Media on Paper","Original",""]
},
{id:'60',
title:"Restructuring Nature",
desc:"Restructuring Nature",
url:"/Artists-Artworks/PreetiSethi/15.jpg",
images:["/Artists-Artworks/PreetiSethi/15.jpg","/Artists-Artworks/PreetiSethi/15.jpg","/Artists-Artworks/PreetiSethi/15.jpg","/Artists-Artworks/PreetiSethi/15.jpg"],
genre:'figurative',
medium:'sculptures',
price:"28000",
artistid:'6',
artistname:'Preeti Sethi',
details:["12 x 12 inches","Metal Art ( Copper)","Original",""]
},
{id:'61',
title:"Dhitrashtra's Mahatvakanksha",
desc:"Dhitrashtra's Mahatvakanksha",
url:"/Artists-Artworks/PreetiSethi/16.jpg",
images:["/Artists-Artworks/PreetiSethi/16.jpg","/Artists-Artworks/PreetiSethi/16.jpg","/Artists-Artworks/PreetiSethi/16.jpg","/Artists-Artworks/PreetiSethi/16.jpg"],
genre:'figurative',
medium:'sculptures',
price:"95000",
artistid:'6',
artistname:'Preeti Sethi',
details:["10 inches","Fibre Sculpture","Original",""]
},
{id:'62',
title:"Bondage",
desc:"Bondage",
url:"/Artists-Artworks/PreetiSethi/17.jpg",
images:["/Artists-Artworks/PreetiSethi/17.jpg","/Artists-Artworks/PreetiSethi/17.jpg","/Artists-Artworks/PreetiSethi/17.jpg","/Artists-Artworks/PreetiSethi/17.jpg"],
genre:'figurative',
medium:'paintings',
price:"15000",
artistid:'6',
artistname:'Preeti Sethi',
details:["11.7 x 16.5 inches","Color Pencil sketch on Paper","Original",""]
},
{id:'63',
title:"Reflections",
desc:"Was selected for the XIIIth Florence Biennale Italy 2021 but I sent only 2 works.",
url:"/Artists-Artworks/PreetiSethi/18.jpg",
images:["/Artists-Artworks/PreetiSethi/18.jpg","/Artists-Artworks/PreetiSethi/18.jpg","/Artists-Artworks/PreetiSethi/18.jpg","/Artists-Artworks/PreetiSethi/18.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'6',
artistname:'Preeti Sethi',
details:["11.7 x 16.5 inches","Color Pencil sketch on Paper","Original",""]
},
{id:'64',
title:"Pawns",
desc:"Pawns",
url:"/Artists-Artworks/PreetiSethi/21.jpg",
images:["/Artists-Artworks/PreetiSethi/21.jpg","/Artists-Artworks/PreetiSethi/21.jpg","/Artists-Artworks/PreetiSethi/21.jpg","/Artists-Artworks/PreetiSethi/21.jpg"],
genre:'figurative',
medium:'paintings',
price:"20000",
artistid:'6',
artistname:'Preeti Sethi',
details:["7 x 9 inches","Original Print on paper","Original",""]
},
{id:'65',
title:"Watchful",
desc:"Watchful",
url:"/Artists-Artworks/PreetiSethi/20.jpg",
images:["/Artists-Artworks/PreetiSethi/20.jpg","/Artists-Artworks/PreetiSethi/20.jpg","/Artists-Artworks/PreetiSethi/20.jpg","/Artists-Artworks/PreetiSethi/20.jpg"],
genre:'figurative',
medium:'paintings',
price:"15000",
artistid:'6',
artistname:'Preeti Sethi',
details:["12 x 12 inches","Original print on fabrino paper","Original",""]
},
{id:'66',
title:"The Market Place",
desc:"The Market Place",
url:"/Artists-Artworks/PreetiSethi/22.jpg",
images:["/Artists-Artworks/PreetiSethi/22.jpg","/Artists-Artworks/PreetiSethi/22.jpg","/Artists-Artworks/PreetiSethi/22.jpg","/Artists-Artworks/PreetiSethi/22.jpg"],
genre:'figurative',
medium:'paintings',
price:"40000",
artistid:'6',
artistname:'Preeti Sethi',
details:["11 x 16 inches","Ink and Charcoal on Paper","Original",""]
},
{id:'67',
title:"Unleashed",
desc:"Unleashed",
url:"/Artists-Artworks/PreetiSethi/1.jpg",
images:["/Artists-Artworks/PreetiSethi/1.jpg","/Artists-Artworks/PreetiSethi/1.jpg","/Artists-Artworks/PreetiSethi/1.jpg","/Artists-Artworks/PreetiSethi/1.jpg"],
genre:'figurative',
medium:'paintings',
price:"70000",
artistid:'6',
artistname:'Preeti Sethi',
details:["24 x 30 inches","Oil on Paper","Original",""]
},
{id:'68',
title:"Flying Elephant",
desc:"Flying Elephant",
url:"/Artists-Artworks/PreetiSethi/14.jpg",
images:["/Artists-Artworks/PreetiSethi/14.jpg","/Artists-Artworks/PreetiSethi/14.jpg","/Artists-Artworks/PreetiSethi/14.jpg","/Artists-Artworks/PreetiSethi/14.jpg"],
genre:'figurative',
medium:'sculptures',
price:"55000",
artistid:'6',
artistname:'Preeti Sethi',
details:["12 x 12 inches","Metal Art ( Brass on Copper Sheet )","Original",""]
},
{id:'69',
title:"Migration",
desc:"Migration",
url:"/Artists-Artworks/PrithujMondal/Migration.JPG",
images:["/Artists-Artworks/PrithujMondal/Migration.JPG","/Artists-Artworks/PrithujMondal/Migration.JPG","/Artists-Artworks/PrithujMondal/Migration.JPG","/Artists-Artworks/PrithujMondal/Migration.JPG"],
genre:'figurative',
medium:'paintings',
price:"200000",
artistid:'5',
artistname:'Prithuj Mondal',
details:["5 x 8 ft","Mixed media on paper","Original",""]
},
{id:'71',
title:"Untitled I",
desc:"Untitled I",
url:"/Artists-Artworks/PrithujMondal/untitledI.JPG",
images:["/Artists-Artworks/PrithujMondal/untitledI.JPG","/Artists-Artworks/PrithujMondal/untitledI.JPG","/Artists-Artworks/PrithujMondal/untitledI.JPG","/Artists-Artworks/PrithujMondal/untitledI.JPG"],
genre:'figurative',
medium:'paintings',
price:"100000",
artistid:'5',
artistname:'Prithuj Mondal',
details:["48 x 48 inches","Mixed media on paper","Original","2019"]
},
{id:'70',
title:"Untitled II",
desc:"Untitled II",
url:"/Artists-Artworks/PrithujMondal/untitledII.JPG",
images:["/Artists-Artworks/PrithujMondal/untitledII.JPG","/Artists-Artworks/PrithujMondal/untitledII.JPG","/Artists-Artworks/PrithujMondal/untitledII.JPG","/Artists-Artworks/PrithujMondal/untitledII.JPG"],
genre:'figurative',
medium:'paintings',
price:"100000",
artistid:'5',
artistname:'Prithuj Mondal',
details:["48 x 48 inches","Mixed media on paper","Original","2019"]
},
{id:'72',
title:"Shelter - 1",
desc:"Shelter - 1",
url:"/Artists-Artworks/DebangsuBiswas/1.jpg",
images:["/Artists-Artworks/DebangsuBiswas/1.jpg","/Artists-Artworks/DebangsuBiswas/1.jpg","/Artists-Artworks/DebangsuBiswas/1.jpg","/Artists-Artworks/DebangsuBiswas/1.jpg"],
genre:'figurative',
medium:'paintings',
price:"70000",
artistid:'7',
artistname:'Debangsu Biswas',
details:["24 x 24 inches","Mixed media on paper","Original",""]
},
{id:'73',
title:"Shelter - 2",
desc:"Shelter - 2",
url:"/Artists-Artworks/DebangsuBiswas/2.jpg",
images:["/Artists-Artworks/DebangsuBiswas/2.jpg","/Artists-Artworks/DebangsuBiswas/2.jpg","/Artists-Artworks/DebangsuBiswas/2.jpg","/Artists-Artworks/DebangsuBiswas/2.jpg"],
genre:'figurative',
medium:'paintings',
price:"70000",
artistid:'7',
artistname:'Debangsu Biswas',
details:["24 x 24 inches","Mixed media on paper","Original",""]
},
{id:'74',
title:"Shelter - 3",
desc:"Shelter - 3",
url:"/Artists-Artworks/DebangsuBiswas/3.jpg",
images:["/Artists-Artworks/DebangsuBiswas/3.jpg","/Artists-Artworks/DebangsuBiswas/3.jpg","/Artists-Artworks/DebangsuBiswas/3.jpg","/Artists-Artworks/DebangsuBiswas/3.jpg"],
genre:'figurative',
medium:'paintings',
price:"70000",
artistid:'7',
artistname:'Debangsu Biswas',
details:["24 x 24 inches","Mixed media on paper","Original",""]
},
{id:'75',
title:"Shelter - 4",
desc:"Shelter - 4",
url:"/Artists-Artworks/DebangsuBiswas/4.jpg",
images:["/Artists-Artworks/DebangsuBiswas/4.jpg","/Artists-Artworks/DebangsuBiswas/4.jpg","/Artists-Artworks/DebangsuBiswas/4.jpg","/Artists-Artworks/DebangsuBiswas/4.jpg"],
genre:'figurative',
medium:'paintings',
price:"70000",
artistid:'7',
artistname:'Debangsu Biswas',
details:["24 x 24 inches","Mixed media on paper","Original",""]
},
{id:'76',
title:"Shelter - 5",
desc:"Shelter - 5",
url:"/Artists-Artworks/DebangsuBiswas/5.jpg",
images:["/Artists-Artworks/DebangsuBiswas/5.jpg","/Artists-Artworks/DebangsuBiswas/5.jpg","/Artists-Artworks/DebangsuBiswas/5.jpg","/Artists-Artworks/DebangsuBiswas/5.jpg"],
genre:'figurative',
medium:'paintings',
price:"70000",
artistid:'7',
artistname:'Debangsu Biswas',
details:["24 x 24 inches","Mixed media on paper","Original",""]
},
{id:'77',
title:"Shelter - 6",
desc:"Shelter - 6",
url:"/Artists-Artworks/DebangsuBiswas/6.jpg",
images:["/Artists-Artworks/DebangsuBiswas/6.jpg","/Artists-Artworks/DebangsuBiswas/6.jpg","/Artists-Artworks/DebangsuBiswas/6.jpg","/Artists-Artworks/DebangsuBiswas/6.jpg"],
genre:'figurative',
medium:'paintings',
price:"70000",
artistid:'7',
artistname:'Debangsu Biswas',
details:["24 x 24 inches","Mixed media on paper","Original",""]
},
{id:'78',
title:"अनंत",
desc:"अनंत",
url:"/Artists-Artworks/Meenugarg/1 (1).png",
images:["/Artists-Artworks/Meenugarg/1 (1).png","/Artists-Artworks/Meenugarg/1 (1).png","/Artists-Artworks/Meenugarg/1 (1).png","/Artists-Artworks/Meenugarg/1 (1).png"],
genre:'figurative',
medium:'paintings',
price:"40000",
artistid:'8',
artistname:'Meenu Garg',
details:["24 x 24 inches","Acrylic on Canvas","Original","2020"]
},
{id:'79',
title:"आत्मचिंतन",
desc:"आत्मचिंतन",
url:"/Artists-Artworks/Meenugarg/1 (2).png",
images:["/Artists-Artworks/Meenugarg/1 (2).png","/Artists-Artworks/Meenugarg/1 (2).png","/Artists-Artworks/Meenugarg/1 (2).png","/Artists-Artworks/Meenugarg/1 (2).png"],
genre:'figurative',
medium:'paintings',
price:"75000",
artistid:'8',
artistname:'Meenu Garg',
details:["30 x 36 inches","Acrylic on Canvas","Original","2020"]
},
{id:'80',
title:"आरंभ",
desc:"आरंभ",
url:"/Artists-Artworks/Meenugarg/1 (3).png",
images:["/Artists-Artworks/Meenugarg/1 (3).png","/Artists-Artworks/Meenugarg/1 (3).png","/Artists-Artworks/Meenugarg/1 (3).png","/Artists-Artworks/Meenugarg/1 (3).png"],
genre:'figurative',
medium:'paintings',
price:"75000",
artistid:'8',
artistname:'Meenu Garg',
details:["30 x 36 inches","Acrylic on Canvas","Original","2021"]
},
{id:'81',
title:"पथिक",
desc:"पथिक",
url:"/Artists-Artworks/Meenugarg/1 (4).png",
images:["/Artists-Artworks/Meenugarg/1 (4).png","/Artists-Artworks/Meenugarg/1 (4).png","/Artists-Artworks/Meenugarg/1 (4).png","/Artists-Artworks/Meenugarg/1 (4).png"],
genre:'figurative',
medium:'paintings',
price:"75000",
artistid:'8',
artistname:'Meenu Garg',
details:["30 x 36 inches","Acrylic on Canvas","Original","2022"]
},
{id:'82',
title:"निर्भय",
desc:"निर्भय",
url:"/Artists-Artworks/Meenugarg/1 (5).png",
images:["/Artists-Artworks/Meenugarg/1 (5).png","/Artists-Artworks/Meenugarg/1 (5).png","/Artists-Artworks/Meenugarg/1 (5).png","/Artists-Artworks/Meenugarg/1 (5).png"],
genre:'figurative',
medium:'paintings',
price:"75000",
artistid:'8',
artistname:'Meenu Garg',
details:["30 x 36 inches","Acrylic on Canvas","Original","2023"]
},
{id:'83',
title:"Recoil",
desc:"Recoil",
url:"/Artists-Artworks/BalwinderTanwar/1 (1).jpg",
images:["/Artists-Artworks/BalwinderTanwar/1 (1).jpg","/Artists-Artworks/BalwinderTanwar/1 (1).jpg","/Artists-Artworks/BalwinderTanwar/1 (1).jpg","/Artists-Artworks/BalwinderTanwar/1 (1).jpg"],
genre:'figurative',
medium:'paintings',
price:"",
artistid:'9',
artistname:'Balwinder Tanwar',
details:["36 x 48 inches","Acrylic on Canvas","Original","2013"]
},
{id:'84',
title:"The forbidden Saint",
desc:"The forbidden Saint",
url:"/Artists-Artworks/BalwinderTanwar/1 (2).jpg",
images:["/Artists-Artworks/BalwinderTanwar/1 (2).jpg","/Artists-Artworks/BalwinderTanwar/1 (2).jpg","/Artists-Artworks/BalwinderTanwar/1 (2).jpg","/Artists-Artworks/BalwinderTanwar/1 (2).jpg"],
genre:'figurative',
medium:'paintings',
price:"",
artistid:'9',
artistname:'Balwinder Tanwar',
details:["36 x 48 inches","Acrylic on Canvas","Original","2013"]
},
{id:'85',
title:"Dreams of Weeds",
desc:"Dreams of Weeds",
url:"/Artists-Artworks/BalwinderTanwar/1 (3).jpg",
images:["/Artists-Artworks/BalwinderTanwar/1 (3).jpg","/Artists-Artworks/BalwinderTanwar/1 (3).jpg","/Artists-Artworks/BalwinderTanwar/1 (3).jpg","/Artists-Artworks/BalwinderTanwar/1 (3).jpg"],
genre:'figurative',
medium:'paintings',
price:"",
artistid:'9',
artistname:'Balwinder Tanwar',
details:["36 x 48 inches","Acrylic on Canvas","Original","January - 2016"]
},
{id:'86',
title:"Saviours",
desc:"Saviours",
url:"/Artists-Artworks/BalwinderTanwar/1 (4).JPG",
images:["/Artists-Artworks/BalwinderTanwar/1 (4).JPG","/Artists-Artworks/BalwinderTanwar/1 (4).JPG","/Artists-Artworks/BalwinderTanwar/1 (4).JPG","/Artists-Artworks/BalwinderTanwar/1 (4).JPG"],
genre:'figurative',
medium:'paintings',
price:"",
artistid:'9',
artistname:'Balwinder Tanwar',
details:["24 x 30 inches","Acrylic on Canvas","Original",""]
},
{id:'87',
title:"The Ravaged Soul",
desc:"The Ravaged Soul",
url:"/Artists-Artworks/BalwinderTanwar/1 (5).JPG",
images:["/Artists-Artworks/BalwinderTanwar/1 (5).JPG","/Artists-Artworks/BalwinderTanwar/1 (5).JPG","/Artists-Artworks/BalwinderTanwar/1 (5).JPG","/Artists-Artworks/BalwinderTanwar/1 (5).JPG"],
genre:'figurative',
medium:'paintings',
price:"",
artistid:'9',
artistname:'Balwinder Tanwar',
details:["36 x 48 inches","Acrylic on Canvas","Original","March - 2014"]
},
{id:'88',
title:"Trapped Dreams",
desc:"Trapped Dreams",
url:"/Artists-Artworks/BalwinderTanwar/1 (6).JPG",
images:["/Artists-Artworks/BalwinderTanwar/1 (6).JPG","/Artists-Artworks/BalwinderTanwar/1 (6).JPG","/Artists-Artworks/BalwinderTanwar/1 (6).JPG","/Artists-Artworks/BalwinderTanwar/1 (6).JPG"],
genre:'figurative',
medium:'paintings',
price:"",
artistid:'9',
artistname:'Balwinder Tanwar',
details:["36 x 48 inches","Acrylic on Canvas","Original","March - 2014"]
},
{id:'89',
    title:"Rays of Hope - 1",
    desc:"Rays of Hope - 1",
    url:"/Artists-Artworks/RavindraKumarTanwar/1.jpg",
    images:["/Artists-Artworks/RavindraKumarTanwar/1.jpg","/Artists-Artworks/RavindraKumarTanwar/1.jpg","/Artists-Artworks/RavindraKumarTanwar/1.jpg","/Artists-Artworks/RavindraKumarTanwar/1.jpg"],
    genre:'',
    medium:'',
    price:"",
    artistid:'10',
    artistname:'Ravindra Kumar Tanwar',
    details:["20 x 30 inches","Digital Print 1-6","Original","2023"]
    },
{id:'90',
    title:"Rays of Hope - 2",
    desc:"Rays of Hope - 2",
    url:"/Artists-Artworks/RavindraKumarTanwar/2.jpg",
    images:["/Artists-Artworks/RavindraKumarTanwar/2.jpg","/Artists-Artworks/RavindraKumarTanwar/2.jpg","/Artists-Artworks/RavindraKumarTanwar/2.jpg","/Artists-Artworks/RavindraKumarTanwar/2.jpg"],
    genre:'',
    medium:'',
    price:"",
    artistid:'10',
    artistname:'Ravindra Kumar Tanwar',
    details:["20 x 30 inches","Digital Print 1-6","Original","2023"]
    },
{id:'91',
    title:"Salvation to Nirvana",
    desc:"Salvation to Nirvana",
    url:"/Artists-Artworks/RavindraKumarTanwar/7.jpg",
    images:["/Artists-Artworks/RavindraKumarTanwar/7.jpg","/Artists-Artworks/RavindraKumarTanwar/7.jpg","/Artists-Artworks/RavindraKumarTanwar/7.jpg","/Artists-Artworks/RavindraKumarTanwar/7.jpg"],
    genre:'',
    medium:'',
    price:"",
    artistid:'10',
    artistname:'Ravindra Kumar Tanwar',
    details:["20 x 30 inches","Print on Archival Paper","Original","2019"]
    },
{id:'92',
    title:"Incredible India...Incredible Holi ...",
    desc:"Incredible India...Incredible Holi ...",
    url:"/Artists-Artworks/RavindraKumarTanwar/3.jpg",
    images:["/Artists-Artworks/RavindraKumarTanwar/3.jpg","/Artists-Artworks/RavindraKumarTanwar/3.jpg","/Artists-Artworks/RavindraKumarTanwar/3.jpg","/Artists-Artworks/RavindraKumarTanwar/3.jpg"],
    genre:'',
    medium:'',
    price:"",
    artistid:'10',
    artistname:'Ravindra Kumar Tanwar',
    details:["20 x 30 inches","Digital Print 1-6","Original","2017"]
    },
{id:'93',
    title:"Incredible India...Incredible Holi ...-II",
    desc:"Incredible India...Incredible Holi ...-II",
    url:"/Artists-Artworks/RavindraKumarTanwar/5.jpg",
    images:["/Artists-Artworks/RavindraKumarTanwar/5.jpg","/Artists-Artworks/RavindraKumarTanwar/5.jpg","/Artists-Artworks/RavindraKumarTanwar/5.jpg","/Artists-Artworks/RavindraKumarTanwar/5.jpg"],
    genre:'',
    medium:'',
    price:"",
    artistid:'10',
    artistname:'Ravindra Kumar Tanwar',
    details:["20 x 30 inches","Print on Archival Paper","Original","2013"]
    },
{id:'94',
    title:"Incredible India...Incredible Holi ...-III",
    desc:"Incredible India...Incredible Holi ...-III",
    url:"/Artists-Artworks/RavindraKumarTanwar/6.jpg",
    images:["/Artists-Artworks/RavindraKumarTanwar/6.jpg","/Artists-Artworks/RavindraKumarTanwar/6.jpg","/Artists-Artworks/RavindraKumarTanwar/6.jpg","/Artists-Artworks/RavindraKumarTanwar/6.jpg"],
    genre:'',
    medium:'',
    price:"",
    artistid:'10',
    artistname:'Ravindra Kumar Tanwar',
    details:["20 x 30 inches","Print on Archival Paper","Original","2013"]
    },
{id:'95',
    title:"Life - 1",
    desc:"Life - 1",
    url:"/Artists-Artworks/PabitraPal/Life1.jpg",
    images:["/Artists-Artworks/PabitraPal/Life1.jpg","/Artists-Artworks/PabitraPal/Life1.jpg","/Artists-Artworks/PabitraPal/Life1.jpg","/Artists-Artworks/PabitraPal/Life1.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["12 x 16 inches","Acrylic color on fabriano paper","Original",""]
    },
{id:'96',
    title:"Life - 2",
    desc:"Life - 2",
    url:"/Artists-Artworks/PabitraPal/Life2.jpg",
    images:["/Artists-Artworks/PabitraPal/Life2.jpg","/Artists-Artworks/PabitraPal/Life2.jpg","/Artists-Artworks/PabitraPal/Life2.jpg","/Artists-Artworks/PabitraPal/Life2.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["12 x 16 inches","Acrylic color on fabriano paper","Original",""]
    },
{id:'97',
    title:"Mesium - 1",
    desc:"Mesium - 1",
    url:"/Artists-Artworks/PabitraPal/Mesium1.jpg",
    images:["/Artists-Artworks/PabitraPal/Mesium1.jpg","/Artists-Artworks/PabitraPal/Mesium1.jpg","/Artists-Artworks/PabitraPal/Mesium1.jpg","/Artists-Artworks/PabitraPal/Mesium1.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["12 x 16 inches","Acrylic color on fabriano paper","Original",""]
    },
{id:'98',
    title:"Mesium - 2",
    desc:"Mesium - 2",
    url:"/Artists-Artworks/PabitraPal/Mesium2.jpg",
    images:["/Artists-Artworks/PabitraPal/Mesium2.jpg","/Artists-Artworks/PabitraPal/Mesium2.jpg","/Artists-Artworks/PabitraPal/Mesium2.jpg","/Artists-Artworks/PabitraPal/Mesium2.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["12 x 16 inches","Acrylic color on fabriano paper","Original",""]
    },
{id:'99',
    title:"My Space - 1",
    desc:"My Space - 1",
    url:"/Artists-Artworks/PabitraPal/MySpace1.jpg",
    images:["/Artists-Artworks/PabitraPal/MySpace1.jpg","/Artists-Artworks/PabitraPal/MySpace1.jpg","/Artists-Artworks/PabitraPal/MySpace1.jpg","/Artists-Artworks/PabitraPal/MySpace1.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["24 x 24 inches","Mixed Media on Board","Original",""]
    },
{id:'100',
    title:"My Space - 2",
    desc:"My Space - 2",
    url:"/Artists-Artworks/PabitraPal/MySpace2.jpg",
    images:["/Artists-Artworks/PabitraPal/MySpace2.jpg","/Artists-Artworks/PabitraPal/MySpace2.jpg","/Artists-Artworks/PabitraPal/MySpace2.jpg","/Artists-Artworks/PabitraPal/MySpace2.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["24 x 24 inches","Mixed Media on Board","Original",""]
    },
{id:'101',
    title:"My Space - 3",
    desc:"My Space - 3",
    url:"/Artists-Artworks/PabitraPal/MySpace3.jpg",
    images:["/Artists-Artworks/PabitraPal/MySpace3.jpg","/Artists-Artworks/PabitraPal/MySpace3.jpg","/Artists-Artworks/PabitraPal/MySpace3.jpg","/Artists-Artworks/PabitraPal/MySpace3.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["24 x 24 inches","Mixed Media on Board","Original",""]
    },
{id:'102',
    title:"My Space - 4",
    desc:"My Space - 4",
    url:"/Artists-Artworks/PabitraPal/MySpace4.jpg",
    images:["/Artists-Artworks/PabitraPal/MySpace4.jpg","/Artists-Artworks/PabitraPal/MySpace4.jpg","/Artists-Artworks/PabitraPal/MySpace4.jpg","/Artists-Artworks/PabitraPal/MySpace4.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["24 x 24 inches","Mixed Media on Board","Original",""]
    },
{id:'103',
    title:"Wings - 1",
    desc:"Wings - 1",
    url:"/Artists-Artworks/PabitraPal/Wingspabitra1.jpg",
    images:["/Artists-Artworks/PabitraPal/Wingspabitra1.jpg","/Artists-Artworks/PabitraPal/Wingspabitra1.jpg","/Artists-Artworks/PabitraPal/Wingspabitra1.jpg","/Artists-Artworks/PabitraPal/Wingspabitra1.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["24 x 24 inches","Mixed Media on Board","Original",""]
    },
{id:'104',
    title:"Wings - 2",
    desc:"Wings - 2",
    url:"/Artists-Artworks/PabitraPal/Wingspabitra2.jpg",
    images:["/Artists-Artworks/PabitraPal/Wingspabitra2.jpg","/Artists-Artworks/PabitraPal/Wingspabitra2.jpg","/Artists-Artworks/PabitraPal/Wingspabitra2.jpg","/Artists-Artworks/PabitraPal/Wingspabitra2.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["24 x 24 inches","Mixed Media on Board","Original",""]
    },
{id:'105',
    title:"Wings - 3",
    desc:"Wings - 3",
    url:"/Artists-Artworks/PabitraPal/Wingspabitra3.jpg",
    images:["/Artists-Artworks/PabitraPal/Wingspabitra3.jpg","/Artists-Artworks/PabitraPal/Wingspabitra3.jpg","/Artists-Artworks/PabitraPal/Wingspabitra3.jpg","/Artists-Artwork/PabitraPal/Wingspabitra3.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["24 x 24 inches","Mixed Media on Board","Original",""]
    },
{id:'106',
    title:"Wings - 4",
    desc:"Wings - 4",
    url:"/Artists-Artworks/PabitraPal/Wingspabitra4.jpg",
    images:["/Artists-Artworks/PabitraPal/Wingspabitra4.jpg","/Artists-Artworks/PabitraPal/Wingspabitra4.jpg","/Artists-Artworks/PabitraPal/Wingspabitra4.jpg","/Artists-Artworks/PabitraPal/Wingspabitra4.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'11',
    artistname:'Pabitra Pal',
    details:["24 x 24 inches","Mixed Media on Board","Original",""]
    },
{id:'107',
    title:"Haven Of Hope",
    desc:"Haven Of Hope",
    url:"/Artists-Artworks/HarshInderLoomba/1.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/1.jpg","/Artists-Artworks/HarshInderLoomba/1.jpg","/Artists-Artworks/HarshInderLoomba/1.jpg","/Artists-Artworks/HarshInderLoomba/1.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["8 x 5 feet","Acrylic on Canvas","Original","September 2022"]
    },
{id:'108',
    title:"Fluids Of Flowers",
    desc:"Fluids Of Flowers",
    url:"/Artists-Artworks/HarshInderLoomba/2.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/2.jpg","/Artists-Artworks/HarshInderLoomba/2.jpg","/Artists-Artworks/HarshInderLoomba/2.jpg","/Artists-Artworks/HarshInderLoomba/2.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["6.5 x 2 feet","Acrylic on Canvas","Original","March 2023"]
    },
{id:'109',
    title:"Lost Heritage",
    desc:"Lost Heritage",
    url:"/Artists-Artworks/HarshInderLoomba/101.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/101.jpg","/Artists-Artworks/HarshInderLoomba/101.jpg","/Artists-Artworks/HarshInderLoomba/101.jpg","/Artists-Artworks/HarshInderLoomba/101.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["24 x 45.5 inches","Acrylic on Canvas","Original","June 2023"]
    },
{id:'110',
    title:"The Maze",
    desc:"The Maze",
    url:"/Artists-Artworks/HarshInderLoomba/5.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/5.jpg","/Artists-Artworks/HarshInderLoomba/5.jpg","/Artists-Artworks/HarshInderLoomba/5.jpg","/Artists-Artworks/HarshInderLoomba/5.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["33.5 x 27.5 inches","Acrylic on Canvas","Original","Nov 2021"]
    },
{id:'111',
    title:"Emerald Realm",
    desc:"Emerald Realm",
    url:"/Artists-Artworks/HarshInderLoomba/6.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/6.jpg","/Artists-Artworks/HarshInderLoomba/6.jpg","/Artists-Artworks/HarshInderLoomba/6.jpg","/Artists-Artworks/HarshInderLoomba/6.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["30 x 34 inches","Acrylic on Canvas","Original","Dec 2023"]
    },
{id:'112',
    title:"Silent Rhyme",
    desc:"Silent Rhyme",
    url:"/Artists-Artworks/HarshInderLoomba/7.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/7.jpg","/Artists-Artworks/HarshInderLoomba/7.jpg","/Artists-Artworks/HarshInderLoomba/7.jpg","/Artists-Artworks/HarshInderLoomba/7.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["30 x 34 inches","Acrylic on Canvas","Original","Dec 2023"]
    },
{id:'113',
    title:"Nature's Symphony",
    desc:"Nature's Symphony",
    url:"/Artists-Artworks/HarshInderLoomba/8.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/8.jpg","/Artists-Artworks/HarshInderLoomba/8.jpg","/Artists-Artworks/HarshInderLoomba/8.jpg","/Artists-Artworks/HarshInderLoomba/8.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["30 x 34 inches","Acrylic on Canvas","Original","Dec 2023"]
    },
{id:'114',
    title:"Portal of Dreams",
    desc:"Portal of Dreams",
    url:"/Artists-Artworks/HarshInderLoomba/9.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/9.jpg","/Artists-Artworks/HarshInderLoomba/9.jpg","/Artists-Artworks/HarshInderLoomba/9.jpg","/Artists-Artworks/HarshInderLoomba/9.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["30 x 34 inches","Acrylic on Canvas","Original","Jan 2024"]
    },
{id:'115',
    title:"Sweet Disposition",
    desc:"Sweet Disposition",
    url:"/Artists-Artworks/HarshInderLoomba/10.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/10.jpg","/Artists-Artworks/HarshInderLoomba/10.jpg","/Artists-Artworks/HarshInderLoomba/10.jpg","/Artists-Artworks/HarshInderLoomba/10.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["A4","Acrylic on Canvas","Original","May 2023"]
    },
{id:'116',
    title:"Polygons of Unity",
    desc:"Polygons of Unity",
    url:"/Artists-Artworks/HarshInderLoomba/11.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/11.jpg","/Artists-Artworks/HarshInderLoomba/11.jpg","/Artists-Artworks/HarshInderLoomba/11.jpg","/Artists-Artworks/HarshInderLoomba/11.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["A4","Acrylic on Canvas","Original","May 2023"]
    },
{id:'117',
    title:"Psychedelic",
    desc:"Psychedelic",
    url:"/Artists-Artworks/HarshInderLoomba/12.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/12.jpg","/Artists-Artworks/HarshInderLoomba/12.jpg","/Artists-Artworks/HarshInderLoomba/12.jpg","/Artists-Artworks/HarshInderLoomba/12.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["A4","Acrylic on Canvas","Original","April 2021"]
    },
{id:'118',
    title:"Primordial Point",
    desc:"Primordial Point",
    url:"/Artists-Artworks/HarshInderLoomba/13.jpg",
    images:["/Artists-Artworks/HarshInderLoomba/13.jpg","/Artists-Artworks/HarshInderLoomba/13.jpg","/Artists-Artworks/HarshInderLoomba/13.jpg","/Artists-Artworks/HarshInderLoomba/13.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"",
    artistid:'12',
    artistname:'Harsh Inder Loomba',
    details:["A4","Acrylic on Canvas","Original","May 2023"]
    },
{id:'119',
    title:"Mirage",
    desc:"Mirage",
    url:"/Artists-Artworks/AjaySamir/1.jpg",
    images:["/Artists-Artworks/AjaySamir/1.jpg","/Artists-Artworks/AjaySamir/1.jpg","/Artists-Artworks/AjaySamir/1.jpg","/Artists-Artworks/AjaySamir/1.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"250000",
    artistid:'13',
    artistname:'Ajay Samir',
    details:["43 x 30 inches","Pen, ink and acrylic colour on acid free paper","Original","2022"]
    },
{id:'120',
    title:"Awakening",
    desc:"Awakening",
    url:"/Artists-Artworks/AjaySamir/2.jpg",
    images:["/Artists-Artworks/AjaySamir/2.jpg","/Artists-Artworks/AjaySamir/2.jpg","/Artists-Artworks/AjaySamir/2.jpg","/Artists-Artworks/AjaySamir/2.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"250000",
    artistid:'13',
    artistname:'Ajay Samir',
    details:["30 x 43 inches","Pen, ink and acrylic colour on acid free paper","Original","2022"]
    },
{id:'121',
    title:"Shakti",
    desc:"Shakti",
    url:"/Artists-Artworks/AjaySamir/3.jpg",
    images:["/Artists-Artworks/AjaySamir/3.jpg","/Artists-Artworks/AjaySamir/3.jpg","/Artists-Artworks/AjaySamir/3.jpg","/Artists-Artworks/AjaySamir/3.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"280000",
    artistid:'13',
    artistname:'Ajay Samir',
    details:["60 x 30 inches","Pen, ink and acrylic colour on acid free paper","Original","2024"]
    },
{id:'122',
    title:"Divine ring",
    desc:"Divine ring",
    url:"/Artists-Artworks/AjaySamir/4.jpg",
    images:["/Artists-Artworks/AjaySamir/4.jpg","/Artists-Artworks/AjaySamir/4.jpg","/Artists-Artworks/AjaySamir/4.jpg","/Artists-Artworks/AjaySamir/4.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"110000",
    artistid:'13',
    artistname:'Ajay Samir',
    details:["22 x 18 inches","Pen, ink and acrylic colour on acid free paper","Original","2023"]
    },
{id:'123',
    title:"Divine sound",
    desc:"Divine sound",
    url:"/Artists-Artworks/AjaySamir/7.jpg",
    images:["/Artists-Artworks/AjaySamir/7.jpg","/Artists-Artworks/AjaySamir/7.jpg","/Artists-Artworks/AjaySamir/7.jpg","/Artists-Artworks/AjaySamir/7.jpg"],
    genre:'figurative',
    medium:'paintings',
    price:"125000",
    artistid:'13',
    artistname:'Ajay Samir',
    details:["24 x 24 inches","Pen, ink and acrylic colour on acid free paper","Original","2021"]
    },
]

export default artworks;