const artworks = [
{id:'1',
title:"Himachal",
desc:"Himachal",
url:"/Artists-Artworks/SusnataChatterjee/himachal.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/himachal.jpeg","/Artists-Artworks/SusnataChatterjee/himachal.jpeg","/Artists-Artworks/SusnataChatterjee/himachal.jpeg","/Artists-Artworks/SusnataChatterjee/himachal.jpeg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["24 x 30 inches","Watercolour on Paper","Original","2024"]
},
{id:'2',
title:"Landscape",
desc:"Landscape",
url:"/Artists-Artworks/SusnataChatterjee/landscape.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/landscape.jpeg","/Artists-Artworks/SusnataChatterjee/landscape.jpeg","/Artists-Artworks/SusnataChatterjee/landscape.jpeg","/Artists-Artworks/SusnataChatterjee/landscape.jpeg"],
genre:'figurative',
medium:'paintings',
price:"73000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["30 x 40 inches","Acrylic on Canvas","Original","2023"]
},
{id:'3',
title:"Photosynthesis",
desc:"Photosynthesis",
url:"/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg","/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg","/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg","/Artists-Artworks/SusnataChatterjee/photosynthesis.jpeg"],
genre:'figurative',
medium:'paintings',
price:"82000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["36 x 42 inches","Acrylic on Canvas","Original","2023"]
},
{id:'4',
title:"Village 2",
desc:"Village 2",
url:"/Artists-Artworks/SusnataChatterjee/village2.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/village2.jpeg","/Artists-Artworks/SusnataChatterjee/village2.jpeg","/Artists-Artworks/SusnataChatterjee/village2.jpeg","/Artists-Artworks/SusnataChatterjee/village2.jpeg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["24 x 30 inches","Watercolour on Paper","Original","2024"]
},
{id:'5',
title:"Peace 1",
desc:"Peace 1",
url:"/Artists-Artworks/SusnataChatterjee/peace.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/peace.jpeg","/Artists-Artworks/SusnataChatterjee/peace.jpeg","/Artists-Artworks/SusnataChatterjee/peace.jpeg","/Artists-Artworks/SusnataChatterjee/peace.jpeg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["24 x 30 inches","Watercolour on Paper","Original","2024"]
},
{id:'6',
title:"Peace 2",
desc:"Peace 2",
url:"/Artists-Artworks/SusnataChatterjee/peace2.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/peace2.jpeg","/Artists-Artworks/SusnataChatterjee/peace2.jpeg","/Artists-Artworks/SusnataChatterjee/peace2.jpeg","/Artists-Artworks/SusnataChatterjee/peace2.jpeg"],
genre:'figurative',
medium:'paintings',
price:"82000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["36 x 42 inches","Acrylic on Canvas","Original","2023"]
},
{id:'7',
title:"Evening",
desc:"Evening",
url:"/Artists-Artworks/SusnataChatterjee/evening.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/evening.jpeg","/Artists-Artworks/SusnataChatterjee/evening.jpeg","/Artists-Artworks/SusnataChatterjee/evening.jpeg","/Artists-Artworks/SusnataChatterjee/evening.jpeg"],
genre:'figurative',
medium:'paintings',
price:"28000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["24 x 30 inches","Acrylic on Canvas","Original","2024"]
},
{id:'8',
title:"Friends",
desc:"Friends",
url:"/Artists-Artworks/SusnataChatterjee/friends.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/friends.jpeg","/Artists-Artworks/SusnataChatterjee/friends.jpeg","/Artists-Artworks/SusnataChatterjee/friends.jpeg","/Artists-Artworks/SusnataChatterjee/friends.jpeg"],
genre:'figurative',
medium:'paintings',
price:"82000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["36 x 42 inches","Acrylic on Canvas","Original","2023"]
},
{id:'9',
title:"The Moon and The Hill Station",
desc:"The Moon and The Hill Station",
url:"/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthehillstation.jpeg"],
genre:'figurative',
medium:'paintings',
price:"82000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["36 x 42 inches","Acrylic on Canvas","Original",""]
},
{id:'10',
title:"Moon and Village",
desc:"Moon and Village",
url:"/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg","/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg","/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg","/Artists-Artworks/SusnataChatterjee/moonandvillage.jpeg"],
genre:'figurative',
medium:'paintings',
price:"64000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["30 x 36 inches","Acrylic on Canvas","Original","2024"]
},
{id:'11',
title:"The Moon and The Village",
desc:"The Moon and The Village",
url:"/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg",
images:["/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg","/Artists-Artworks/SusnataChatterjee/themoonandthevillage.jpeg"],
genre:'figurative',
medium:'paintings',
price:"37000",
artistid:'1',
artistname:'Susnata Chatterjee',
details:["30 x 36 inches","Acrylic on Canvas","Original","2024"]
},
{id:'12',
title:"Bija/ Hope 1",
desc:"Bija/ Hope 1",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (1).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["13 x 11 inches","Acrylic on Canvas","Original","2024"]
},
{id:'13',
title:"Bija/ Hope 2",
desc:"Bija/ Hope 2",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (2).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["13 x 11 inches","Acrylic on Canvas","Original","2024"]
},
{id:'14',
title:"Bija/ Hope 3",
desc:"Bija/ Hope 3",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (3).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["13 x 11 inches","Acrylic on Canvas","Original","2024"]
},
{id:'15',
title:"Bija/ Hope 4",
desc:"Bija/ Hope 4",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (4).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["13 x 13 inches","Acrylic on Canvas","Original","2024"]
},
{id:'16',
title:"Bija/ Hope 5",
desc:"Bija/ Hope 5",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (5).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["13 x 13 inches","Acrylic on Canvas","Original","2024"]
},
{id:'17',
title:"Bija/ Hope 6",
desc:"Bija/ Hope 6",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (6).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["13 x 13 inches","Acrylic on Canvas","Original","2024"]
},
{id:'18',
title:"Bija/ Hope 7",
desc:"Bija/ Hope 7",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (7).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["13 x 13 inches","Acrylic on Canvas","Original","2024"]
},
{id:'19',
title:"Bija/ Hope 8",
desc:"Bija/ Hope 8",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (8).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["14 x 11 inches","Acrylic on Canvas","Original","2024"]
},
{id:'20',
title:"Bija/ Hope 9",
desc:"Bija/ Hope 9",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (9).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["15 x 15 inches","Acrylic on Canvas","Original","2024"]
},
{id:'21',
title:"Bija/ Hope 10",
desc:"Bija/ Hope 10",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (10).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["15 x 15 inches","Acrylic on Canvas","Original","2024"]
},
{id:'22',
title:"Bija/ Hope 11",
desc:"Bija/ Hope 11",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (11).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["15 x 15 inches","Acrylic on Canvas","Original","2024"]
},
{id:'23',
title:"Bija/ Hope 12",
desc:"Bija/ Hope 12",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (12).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["20 x 20 inches","Acrylic on Canvas","Original","2024"]
},
{id:'24',
title:"Bija/ Hope 13",
desc:"Bija/ Hope 13",
url:"/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg","/Artists-Artworks/SubrataGhosh/Bija/price25k/bija (13).jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["20 x 20 inches","Acrylic on Canvas","Original","2024"]
},
{id:'25',
title:"Bija/ Hope 14",
desc:"Bija/ Hope 14",
url:"/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (1).jpg"],
genre:'figurative',
medium:'paintings',
price:"35000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["32 x 30 inches","Acrylic on Canvas","Original","2024"]
},
{id:'26',
title:"Bija/ Hope 15",
desc:"Bija/ Hope 15",
url:"/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg",
images:["/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg","/Artists-Artworks/SubrataGhosh/Bija/price35k/bija (2).jpg"],
genre:'figurative',
medium:'paintings',
price:"35000",
artistid:'2',
artistname:'Subrata Ghosh',
details:["30 x 36 inches","Acrylic on Canvas","Original","2024"]
},
{id:'27',
title:"Submerged IV",
desc:"Submerged IV",
url:"/Artists-Artworks/TitasDas/submergediv.jpg",
images:["/Artists-Artworks/TitasDas/submergediv.jpg","/Artists-Artworks/TitasDas/submergediv.jpg","/Artists-Artworks/TitasDas/submergediv.jpg","/Artists-Artworks/TitasDas/submergediv.jpg"],
genre:'figurative',
medium:'paintings',
price:"99000",
artistid:'3',
artistname:'Titas Das',
details:["48 x 56 inches","Acrylic on Canvas","Original","2023"]
},
{id:'28',
title:"Submerged IX",
desc:"Submerged IX",
url:"/Artists-Artworks/TitasDas/submergedix.jpg",
images:["/Artists-Artworks/TitasDas/submergedix.jpg","/Artists-Artworks/TitasDas/submergedix.jpg","/Artists-Artworks/TitasDas/submergedix.jpg","/Artists-Artworks/TitasDas/submergedix.jpg"],
genre:'figurative',
medium:'paintings',
price:"99000",
artistid:'3',
artistname:'Titas Das',
details:["48 x 56 inches","Acrylic on Canvas","Original","2023"]
},
{id:'29',
title:"Submerged X",
desc:"Submerged X",
url:"/Artists-Artworks/TitasDas/submergedx.jpg",
images:["/Artists-Artworks/TitasDas/submergedx.jpg","/Artists-Artworks/TitasDas/submergedx.jpg","/Artists-Artworks/TitasDas/submergedx.jpg","/Artists-Artworks/TitasDas/submergedx.jpg"],
genre:'figurative',
medium:'paintings',
price:"99000",
artistid:'3',
artistname:'Titas Das',
details:["48 x 56 inches","Acrylic on Canvas","Original","2023"]
},
{id:'30',
title:"Submerged XI",
desc:"Submerged XI",
url:"/Artists-Artworks/TitasDas/submergedxi.jpg",
images:["/Artists-Artworks/TitasDas/submergedxi.jpg","/Artists-Artworks/TitasDas/submergedxi.jpg","/Artists-Artworks/TitasDas/submergedxi.jpg","/Artists-Artworks/TitasDas/submergedxi.jpg"],
genre:'figurative',
medium:'paintings',
price:"79000",
artistid:'3',
artistname:'Titas Das',
details:["32 x 56 inches","Acrylic on Canvas","Original","2023"]
},
{id:'31',
title:"Submerged XXXIII",
desc:"Submerged XXXIII",
url:"/Artists-Artworks/TitasDas/submergedxxxiii.jpg",
images:["/Artists-Artworks/TitasDas/submergedxxxiii.jpg","/Artists-Artworks/TitasDas/submergedxxxiii.jpg","/Artists-Artworks/TitasDas/submergedxxxiii.jpg","/Artists-Artworks/TitasDas/submergedxxxiii.jpg"],
genre:'figurative',
medium:'paintings',
price:"69000",
artistid:'3',
artistname:'Titas Das',
details:["30 x 48 inches","Acrylic on Canvas","Original","2023"]
},
{id:'32',
title:"Sadhna",
desc:"Sadhna",
url:"/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg",
images:["/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg","/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg","/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg","/Artists-Artworks/MitaliRoyChoudhury/sadhna.jpg"],
genre:'figurative',
medium:'paintings',
price:"9000",
artistid:'4',
artistname:'Mitali Roy Choudhury',
details:["24 x 24 inches","Applique Work on Canvas","Original","2024"]
},
{id:'33',
title:"O Deer",
desc:"O Deer",
url:"/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg",
images:["/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg","/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg","/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg","/Artists-Artworks/MitaliRoyChoudhury/odeer.jpg"],
genre:'figurative',
medium:'paintings',
price:"7000",
artistid:'4',
artistname:'Mitali Roy Choudhury',
details:["17 x 37 inches","Applique Work on Canvas","Original","2024"]
},
{id:'34',
title:"City Roads",
desc:"City Roads",
url:"/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg",
images:["/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg","/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg","/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg","/Artists-Artworks/MitaliRoyChoudhury/cityroads.jpg"],
genre:'figurative',
medium:'paintings',
price:"7000",
artistid:'4',
artistname:'Mitali Roy Choudhury',
details:["17 x 37 inches","Applique Work on Canvas","Original","2024"]
},
{id:'35',
title:"Lotus Pond",
desc:"Lotus Pond",
url:"/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg",
images:["/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg","/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg","/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg","/Artists-Artworks/MitaliRoyChoudhury/lotuspond.jpg"],
genre:'figurative',
medium:'paintings',
price:"7000",
artistid:'4',
artistname:'Mitali Roy Choudhury',
details:["17 x 37 inches","Applique Work on Cloth","Original","2024"]
},
{id:'36',
title:"Discuss",
desc:"Discuss",
url:"/Artists-Artworks/ShayaniBoral/discuss.jpg",
images:["/Artists-Artworks/ShayaniBoral/discuss.jpg","/Artists-Artworks/ShayaniBoral/discuss.jpg","/Artists-Artworks/ShayaniBoral/discuss.jpg","/Artists-Artworks/ShayaniBoral/discuss.jpg"],
genre:'figurative',
medium:'paintings',
price:"50000",
artistid:'5',
artistname:'Shayani Boral',
details:["48 x 60 inches","Acrylic (mixed media)","Original",""]
},
{id:'37',
title:"The Garden of Galleria",
desc:"The Garden of Galleria",
url:"/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg",
images:["/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg","/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg","/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg","/Artists-Artworks/ShayaniBoral/thegardenofgalleria.jpg"],
genre:'figurative',
medium:'paintings',
price:"150000",
artistid:'5',
artistname:'Shayani Boral',
details:["82 x 55 inches","Mixed Media on Canvas","Original",""]
},
{id:'38',
title:"Turtle's Tapestry",
desc:"Turtle's Tapestry",
url:"/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg",
images:["/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg","/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg","/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg","/Artists-Artworks/ShayaniBoral/turtlestapestry.jpg"],
genre:'figurative',
medium:'paintings',
price:"50000",
artistid:'5',
artistname:'Shayani Boral',
details:["48 x 36 inches","Ink, Brush, Pen & Acrylic (mixed media)","Original",""]
},
{id:'39',
title:"Resonance of Nature",
desc:"Resonance of Nature",
url:"/Artists-Artworks/ShayaniBoral/resonanceofnature.jpg",
images:["/Artists-Artworks/ShayaniBoral/resonanceofnature.jpg","/Artists-Artworks/ShayaniBoral/resonanceofnature.jpg","/Artists-Artworks/ShayaniBoral/resonanceofnature.jpg","/Artists-Artworks/ShayaniBoral/resonanceofnature.jpg"],
genre:'figurative',
medium:'paintings',
price:"50000",
artistid:'5',
artistname:'Shayani Boral',
details:["48 x 60 inches","Acrylic on Canvas","Original",""]
},
{id:'40',
title:"Turmoil in Sea Bed",
desc:"Turmoil in Sea Bed",
url:"/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg",
images:["/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg","/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg","/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg","/Artists-Artworks/ShayaniBoral/turmoilinseabed.jpg"],
genre:'figurative',
medium:'paintings',
price:"500000",
artistid:'5',
artistname:'Shayani Boral',
details:["48 x 60 inches","Mixed Media on Canvas","Original",""]
},
{id:'41',
title:"Urban Drought",
desc:"Urban Drought",
url:"/Artists-Artworks/ShayaniBoral/urbandrought.jpg",
images:["/Artists-Artworks/ShayaniBoral/urbandrought.jpg","/Artists-Artworks/ShayaniBoral/urbandrought.jpg","/Artists-Artworks/ShayaniBoral/urbandrought.jpg","/Artists-Artworks/ShayaniBoral/urbandrought.jpg"],
genre:'figurative',
medium:'paintings',
price:"150000",
artistid:'5',
artistname:'Shayani Boral',
details:["8ft x 4ft","Mixed Media on Canvas","Original",""]
},
{id:'42',
title:"Urban Traffic",
desc:"Urban Traffic",
url:"/Artists-Artworks/ShayaniBoral/urbantraffic.jpg",
images:["/Artists-Artworks/ShayaniBoral/urbantraffic.jpg","/Artists-Artworks/ShayaniBoral/urbantraffic.jpg","/Artists-Artworks/ShayaniBoral/urbantraffic.jpg","/Artists-Artworks/ShayaniBoral/urbantraffic.jpg"],
genre:'figurative',
medium:'paintings',
price:"350000",
artistid:'5',
artistname:'Shayani Boral',
details:["28 x 30 inches","Mixed Media on Canvas","Original",""]
},
{id:'43',
title:"Urban Check Mate",
desc:"Urban Check Mate",
url:"/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg",
images:["/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg","/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg","/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg","/Artists-Artworks/ShayaniBoral/urbancheckmate.jpg"],
genre:'figurative',
medium:'paintings',
price:"150000",
artistid:'5',
artistname:'Shayani Boral',
details:["48 x 54 inches","Mixed Media on Canvas","Original",""]
},
{id:'44',
title:"1000 Miles",
desc:"1000 Miles",
url:"/Artists-Artworks/PrithujMondal/1000miles.jpg",
images:["/Artists-Artworks/PrithujMondal/1000miles.jpg","/Artists-Artworks/PrithujMondal/1000miles.jpg","/Artists-Artworks/PrithujMondal/1000miles.jpg","/Artists-Artworks/PrithujMondal/1000miles.jpg"],
genre:'figurative',
medium:'paintings',
price:"150000",
artistid:'6',
artistname:'Prithuj Mondal',
details:["72 x 48 inches","Dry Pastel on Paper","Original","2020"]
},
{id:'45',
title:"Conversation",
desc:"Conversation",
url:"/Artists-Artworks/PrithujMondal/conversation.jpg",
images:["/Artists-Artworks/PrithujMondal/conversation.jpg","/Artists-Artworks/PrithujMondal/conversation.jpg","/Artists-Artworks/PrithujMondal/conversation.jpg","/Artists-Artworks/PrithujMondal/conversation.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'6',
artistname:'Prithuj Mondal',
details:["24 x 24 inches","Acrylic on Canvas","Original","2022"]
},
{id:'46',
title:"Once Upon a Time",
desc:"Once Upon a Time",
url:"/Artists-Artworks/PrithujMondal/onceuponatime.jpg",
images:["/Artists-Artworks/PrithujMondal/onceuponatime.jpg","/Artists-Artworks/PrithujMondal/onceuponatime.jpg","/Artists-Artworks/PrithujMondal/onceuponatime.jpg","/Artists-Artworks/PrithujMondal/onceuponatime.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'6',
artistname:'Prithuj Mondal',
details:["24 x 24 inches","Acrylic on Canvas","Original","2022"]
},
{id:'47',
title:"The Angels",
desc:"The Angels",
url:"/Artists-Artworks/PrithujMondal/theangels.jpg",
images:["/Artists-Artworks/PrithujMondal/theangels.jpg","/Artists-Artworks/PrithujMondal/theangels.jpg","/Artists-Artworks/PrithujMondal/theangels.jpg","/Artists-Artworks/PrithujMondal/theangels.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'6',
artistname:'Prithuj Mondal',
details:["24 x 24 inches","Acrylic on Canvas","Original","2022"]
},
{id:'48',
title:"Untitled",
desc:"Untitled",
url:"/Artists-Artworks/PrithujMondal/untitled.jpg",
images:["/Artists-Artworks/PrithujMondal/untitled.jpg","/Artists-Artworks/PrithujMondal/untitled.jpg","/Artists-Artworks/PrithujMondal/untitled.jpg","/Artists-Artworks/PrithujMondal/untitled.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'6',
artistname:'Prithuj Mondal',
details:["24 x 24 inches","Acrylic on Canvas","Original","2022"]
},
{id:'49',
title:"Moods",
desc:"Moods",
url:"/Artists-Artworks/PreetiSethi/2.jpg",
images:["/Artists-Artworks/PreetiSethi/2.jpg","/Artists-Artworks/PreetiSethi/2.jpg","/Artists-Artworks/PreetiSethi/2.jpg","/Artists-Artworks/PreetiSethi/2.jpg"],
genre:'figurative',
medium:'paintings',
price:"15000",
artistid:'7',
artistname:'Preeti Sethi',
details:["A4","Print on Archival Paper","Original",""]
},
{id:'50',
title:"The Leap",
desc:"The Leap",
url:"/Artists-Artworks/PreetiSethi/3.jpg",
images:["/Artists-Artworks/PreetiSethi/3.jpg","/Artists-Artworks/PreetiSethi/3.jpg","/Artists-Artworks/PreetiSethi/3.jpg","/Artists-Artworks/PreetiSethi/3.jpg"],
genre:'figurative',
medium:'paintings',
price:"295000",
artistid:'7',
artistname:'Preeti Sethi',
details:["24 x 36 inches","Mixed Media (Brass Metal Art) on Canvas","Original",""]
},
{id:'51',
title:"Amba's Pratishodh",
desc:"Amba's Pratishodh",
url:"/Artists-Artworks/PreetiSethi/4.jpg",
images:["/Artists-Artworks/PreetiSethi/4.jpg","/Artists-Artworks/PreetiSethi/5.jpg","/Artists-Artworks/PreetiSethi/41.jpg","/Artists-Artworks/PreetiSethi/4.jpg"],
genre:'figurative',
medium:'paintings',
price:"125000",
artistid:'7',
artistname:'Preeti Sethi',
details:["18 inches","Fibre","Original",""]
},
{id:'52',
title:"Karma",
desc:"Was selected to be exhibited at the XIV th Florence Biennale Italy 2023 ( I did not participate due to personal issues)",
url:"/Artists-Artworks/PreetiSethi/6.jpg",
images:["/Artists-Artworks/PreetiSethi/6.jpg","/Artists-Artworks/PreetiSethi/6.jpg","/Artists-Artworks/PreetiSethi/6.jpg","/Artists-Artworks/PreetiSethi/6.jpg"],
genre:'figurative',
medium:'paintings',
price:"110000",
artistid:'7',
artistname:'Preeti Sethi',
details:["3 x 4 ft","Mixed Media on Canvas","Original",""]
},
{id:'53',
title:"It's a Girl!!!!",
desc:"Was exhibited at the XIIIth Florence Biennale Italy 2021",
url:"/Artists-Artworks/PreetiSethi/7.jpg",
images:["/Artists-Artworks/PreetiSethi/7.jpg","/Artists-Artworks/PreetiSethi/7.jpg","/Artists-Artworks/PreetiSethi/7.jpg","/Artists-Artworks/PreetiSethi/7.jpg"],
genre:'figurative',
medium:'paintings',
price:"On Request",
artistid:'7',
artistname:'Preeti Sethi',
details:["12 x 12 inches","Mixed Medium Clay Sculpture ","Original",""]
},
{id:'54',
title:"Might",
desc:"Might",
url:"/Artists-Artworks/PreetiSethi/8.jpg",
images:["/Artists-Artworks/PreetiSethi/8.jpg","/Artists-Artworks/PreetiSethi/8.jpg","/Artists-Artworks/PreetiSethi/8.jpg","/Artists-Artworks/PreetiSethi/8.jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'7',
artistname:'Preeti Sethi',
details:["10 x 10 inches","Mixed Media on Paper","Original",""]
},
{id:'55',
title:"Lust",
desc:"Lust",
url:"/Artists-Artworks/PreetiSethi/9.jpg",
images:["/Artists-Artworks/PreetiSethi/9.jpg","/Artists-Artworks/PreetiSethi/9.jpg","/Artists-Artworks/PreetiSethi/9.jpg","/Artists-Artworks/PreetiSethi/9.jpg"],
genre:'figurative',
medium:'paintings',
price:"35000",
artistid:'7',
artistname:'Preeti Sethi',
details:["10 x 10 inches","Mixed Media on Paper","Original",""]
},
{id:'56',
title:"Tattered Wings and Shattered Dreams",
desc:"Tattered Wings and Shattered Dreams",
url:"/Artists-Artworks/PreetiSethi/10.jpg",
images:["/Artists-Artworks/PreetiSethi/10.jpg","/Artists-Artworks/PreetiSethi/10.jpg","/Artists-Artworks/PreetiSethi/10.jpg","/Artists-Artworks/PreetiSethi/10.jpg"],
genre:'figurative',
medium:'paintings',
price:"35000",
artistid:'7',
artistname:'Preeti Sethi',
details:["10 x 10 inches","Color Pencils on paper","Original",""]
},
{id:'57',
title:"Eklavyas Gurudhakshina",
desc:"Eklavyas Gurudhakshina",
url:"/Artists-Artworks/PreetiSethi/11.jpg",
images:["/Artists-Artworks/PreetiSethi/11.jpg","/Artists-Artworks/PreetiSethi/11.jpg","/Artists-Artworks/PreetiSethi/11.jpg","/Artists-Artworks/PreetiSethi/11.jpg"],
genre:'figurative',
medium:'paintings',
price:"105000",
artistid:'7',
artistname:'Preeti Sethi',
details:["18 inches","Fibre Sculpture","Original",""]
},
{id:'58',
title:"Pawns-1",
desc:"Pawns-1",
url:"/Artists-Artworks/PreetiSethi/12.jpg",
images:["/Artists-Artworks/PreetiSethi/12.jpg","/Artists-Artworks/PreetiSethi/12.jpg","/Artists-Artworks/PreetiSethi/12.jpg","/Artists-Artworks/PreetiSethi/12.jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'7',
artistname:'Preeti Sethi',
details:["12 x 12 inches","Acrylic on Canvas","Original",""]
},
{id:'59',
title:"Scars-2",
desc:"Scars-2",
url:"/Artists-Artworks/PreetiSethi/13.jpg",
images:["/Artists-Artworks/PreetiSethi/13.jpg","/Artists-Artworks/PreetiSethi/13.jpg","/Artists-Artworks/PreetiSethi/13.jpg","/Artists-Artworks/PreetiSethi/13.jpg"],
genre:'figurative',
medium:'paintings',
price:"25000",
artistid:'7',
artistname:'Preeti Sethi',
details:["10 x 10 inches","Mixed Media on Paper","Original",""]
},
{id:'60',
title:"Restructuring Nature",
desc:"Restructuring Nature",
url:"/Artists-Artworks/PreetiSethi/15.jpg",
images:["/Artists-Artworks/PreetiSethi/15.jpg","/Artists-Artworks/PreetiSethi/15.jpg","/Artists-Artworks/PreetiSethi/15.jpg","/Artists-Artworks/PreetiSethi/15.jpg"],
genre:'figurative',
medium:'paintings',
price:"28000",
artistid:'7',
artistname:'Preeti Sethi',
details:["12 x 12 inches","Metal Art ( Copper)","Original",""]
},
{id:'61',
title:"Dhitrashtra's Mahatvakanksha",
desc:"Dhitrashtra's Mahatvakanksha",
url:"/Artists-Artworks/PreetiSethi/16.jpg",
images:["/Artists-Artworks/PreetiSethi/16.jpg","/Artists-Artworks/PreetiSethi/16.jpg","/Artists-Artworks/PreetiSethi/16.jpg","/Artists-Artworks/PreetiSethi/16.jpg"],
genre:'figurative',
medium:'paintings',
price:"95000",
artistid:'7',
artistname:'Preeti Sethi',
details:["10 inches","Fibre Sculpture","Original",""]
},
{id:'62',
title:"Bondage",
desc:"Bondage",
url:"/Artists-Artworks/PreetiSethi/17.jpg",
images:["/Artists-Artworks/PreetiSethi/17.jpg","/Artists-Artworks/PreetiSethi/17.jpg","/Artists-Artworks/PreetiSethi/17.jpg","/Artists-Artworks/PreetiSethi/17.jpg"],
genre:'figurative',
medium:'paintings',
price:"15000",
artistid:'7',
artistname:'Preeti Sethi',
details:["11.7 x 16.5 inches","Color Pencil sketch on Paper","Original",""]
},
{id:'63',
title:"Reflections",
desc:"Was selected for the XIIIth Florence Biennale Italy 2021 but I sent only 2 works.",
url:"/Artists-Artworks/PreetiSethi/18.jpg",
images:["/Artists-Artworks/PreetiSethi/18.jpg","/Artists-Artworks/PreetiSethi/18.jpg","/Artists-Artworks/PreetiSethi/18.jpg","/Artists-Artworks/PreetiSethi/18.jpg"],
genre:'figurative',
medium:'paintings',
price:"65000",
artistid:'7',
artistname:'Preeti Sethi',
details:["11.7 x 16.5 inches","Color Pencil sketch on Paper","Original",""]
},
{id:'64',
title:"Pawns",
desc:"Pawns",
url:"/Artists-Artworks/PreetiSethi/21.jpg",
images:["/Artists-Artworks/PreetiSethi/21.jpg","/Artists-Artworks/PreetiSethi/21.jpg","/Artists-Artworks/PreetiSethi/21.jpg","/Artists-Artworks/PreetiSethi/21.jpg"],
genre:'figurative',
medium:'paintings',
price:"20000",
artistid:'7',
artistname:'Preeti Sethi',
details:["7 x 9 inches","Original Print on paper","Original",""]
},
{id:'65',
title:"Watchful",
desc:"Watchful",
url:"/Artists-Artworks/PreetiSethi/20.jpg",
images:["/Artists-Artworks/PreetiSethi/20.jpg","/Artists-Artworks/PreetiSethi/20.jpg","/Artists-Artworks/PreetiSethi/20.jpg","/Artists-Artworks/PreetiSethi/20.jpg"],
genre:'figurative',
medium:'paintings',
price:"15000",
artistid:'7',
artistname:'Preeti Sethi',
details:["12 x 12 inches","Original print on fabrino paper","Original",""]
},
{id:'66',
title:"The Market Place",
desc:"The Market Place",
url:"/Artists-Artworks/PreetiSethi/22.jpg",
images:["/Artists-Artworks/PreetiSethi/22.jpg","/Artists-Artworks/PreetiSethi/22.jpg","/Artists-Artworks/PreetiSethi/22.jpg","/Artists-Artworks/PreetiSethi/22.jpg"],
genre:'figurative',
medium:'paintings',
price:"40000",
artistid:'7',
artistname:'Preeti Sethi',
details:["11 x 16 inches","Ink and Charcoal on Paper","Original",""]
},
]

export default artworks;