import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar'
import Hero from '../components/homepage/herocomponent'
import Events from '../components/homepage/events'
import Footer from '../components/footer'
import React from 'react';
import dynamic from "next/dynamic";
import data from './api/artdata'
import OurServices from '@/components/homepage/OurServices'
import ArtworksSlider from '@/components/homepage/ArtworksSlider'
import artworks from './api/artworks'
import StandOut from '@/components/homepage/StandOut'
import Subscriptions from '@/components/homepage/Subscriptions'
import Artists from '@/components/homepage/Artists'
import SmoothScroll from '@/components/SmoothScroll/SmoothScroll.js'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  
  return (
    <>
      <Head>
        <title>Hyperglot Art</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <main className={styles.mainpage}>
          <Navbar />
          <SmoothScroll>
          <Hero />
          <OurServices />
          <ArtworksSlider artworks={artworks}/>
          <StandOut />
          <Subscriptions />
          <Artists data={data}/>
          <Events />

          <Footer />
          </SmoothScroll>
      </main>        
      
    </>
  )
}

export default dynamic (() => Promise.resolve(Home), {ssr: false})
