import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar'
import Hero from '../components/homepage/herocomponent'
import Herobutton from '../components/homepage/herobutton'
import Slider from '../components/homepage/slider'
import Featured from '../components/homepage/featured'
import Events from '../components/homepage/events'
import Collection from '../components/homepage/collection'
import Footer from '../components/footer'
import React from 'react';
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ['latin'] })


export const getStaticProps = async () => {
  const resulting = await fetch(`${process.env.NEXT_PUBLIC_URL}/products?populate=*`, {
    headers: {
     Authorization: "bearer "+process.env.NEXT_PUBLIC_TOKEN,
   } 
   });
  const result = await resulting.json();
  return {
    props: {
      product: result.data,
    },
  };
};

const Home = ({product}) => {
  
  return (
    <>
      <Head>
        <title>Hyperglot Art</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <main>
        <Navbar />
        <Hero />
        <Herobutton />
        <Slider product={product}/>
        <Featured />
        <Events />
        <Collection product={product}/>
        <Footer />
      </main>        
      
    </>
  )
}

export default dynamic (() => Promise.resolve(Home), {ssr: false})
