import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar'
import Hero from '../components/homepage/herocomponent'
import Herobutton from '../components/homepage/herobutton'
import Slider from '../components/homepage/slider'
import Featured from '../components/homepage/featured'
import Events from '../components/homepage/events'
import Collection from '../components/homepage/collection'
import Footer from '../components/footer'
import LoadingScreen from '../components/loader/loader';
import React from 'react';
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 500);
  }, []);

  
  return (
    <>
      <Head>
        <title>Hyperglot Art</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      {!loading ? (
      <main>
        <Navbar />
        <Hero />
        <Herobutton />
        <Slider />
        <Featured />
        <Events />
        <Collection />
        <Footer />
      </main>        
      ) : (
      <LoadingScreen />
    )}
      
    </>
  )
}
